<?php
/*
 * Generated configuration file
 * Generated by: phpMyAdmin 2.11.10 setup script by Michal ДЊihaЕ™ <michal@cihar.com>
 * Version: $Id: setup.php 13149 2009-12-07 13:09:09Z nijel $
 * Date: Sun, 13 Jun 2010 15:02:53 GMT
 */

/* Servers configuration */
$i = 0;

/* Server localhost (cookie) [1] */
$i++;
$cfg['Servers'][$i]['host'] = 'localhost';
$cfg['Servers'][$i]['extension'] = 'mysql';
$cfg['Servers'][$i]['connect_type'] = 'tcp';
$cfg['Servers'][$i]['compress'] = false;
$cfg['Servers'][$i]['auth_type'] = 'cookie';

$cfg['Servers'][$i]['AllowDeny']['order'] = '';

$cfg['Servers'][$i]['AllowDeny']['rules'] = array();



/* End of servers configuration */

$cfg['blowfish_secret'] = '4c14f2ec6d44d5.84658931';
?>
